# **Penting**
- Jangan menambahkan import libary atau function apa pun, selain yang sudah tersedia pada cell code atau yang diperbolehkan.
- Misal, Anda ingin membangun lebih dari satu model selain decision tree, yang mana itu diperbolehkan dalam instruksi, maka diperbolehkan untuk menambahkan beberapa code selain bagian yang rumpang.
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Ingat, tugas Anda hanyalah melengkapi code yang rumpang pada bagian yang sudah ditandai "________" saja.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan juga output yang dihasilkan sesuai dengan output yang diharapkan (expected output). Sehingga Anda dapat mereview sendiri terlebih dahulu output dari cell code yang dijalankan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report
import joblib

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [36]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]

### MULAI CODE ###

df = pd.read_csv("data_clustering.csv")

### SELESAI CODE ###

In [37]:
# Tampilkan 5 baris pertama dengan function head

### MULAI CODE ###

df.head()

### SELESAI CODE ###

,CounterpartyAccount,TransactionAmount,TransactionType,MerchantCategory,Location,DeviceType,IsFraud,FraudType,TimeSinceLastTransaction,SpendingDeviationScore,VelocityScore,GeoAnomalyScore,PaymentChannel,TransactionAmountBinned,Target
0,4,-0.784733,3,1,4,1,True,0,-0.947270,-0.881191,0.681689,-0.508128,0,0,0
1,5,1.742413,0,0,0,0,True,0,0.523973,0.513942,-0.616766,-0.709367,1,2,0
2,1,-0.862050,2,3,0,0,True,0,1.991598,0.914017,-0.292152,-0.558438,0,0,0
3,0,1.642675,0,2,3,1,True,0,-1.393581,0.216451,-1.752914,1.604880,0,2,0
4,3,-0.843655,1,2,4,2,True,0,-0.065342,0.267742,-0.779073,-1.967110,1,0,0

## **(OPSIONAL) Feature Encoding: One Hot Encoding**
Langkah ini **HANYA** dilakukan saat Anda menggunakan **data hasil Inverse** untuk memenuhi kriteria Advanced pada latihan sebelumnya.

In [38]:
### MULAI CODE OPSIONAL ###

categorical_cols = list(df.select_dtypes(include=['object']).columns)

# Gunakan 'pd.get_dummies' untuk melakukan OneHotEncoding
df_encoded = pd.get_dummies(
    df,
    columns = categorical_cols,
    drop_first = True
)

# Tampilkan 5 baris pertama untuk memverifikasi hasilnya
df_encoded.head()

### SELESEI CODE OPSIONAL ###

,CounterpartyAccount,TransactionAmount,TransactionType,MerchantCategory,Location,DeviceType,IsFraud,FraudType,TimeSinceLastTransaction,SpendingDeviationScore,VelocityScore,GeoAnomalyScore,PaymentChannel,TransactionAmountBinned,Target
0,4,-0.784733,3,1,4,1,True,0,-0.947270,-0.881191,0.681689,-0.508128,0,0,0
1,5,1.742413,0,0,0,0,True,0,0.523973,0.513942,-0.616766,-0.709367,1,2,0
2,1,-0.862050,2,3,0,0,True,0,1.991598,0.914017,-0.292152,-0.558438,0,0,0
3,0,1.642675,0,2,3,1,True,0,-1.393581,0.216451,-1.752914,1.604880,0,2,0
4,3,-0.843655,1,2,4,2,True,0,-0.065342,0.267742,-0.779073,-1.967110,1,0,0

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [39]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.

### MULAI CODE ###

# Buat 'X' dengan menghapus 'Target' dari 'df_encoded' dan gunakan 'axis=1' untuk menandakan drop kolom.
X = df_encoded.drop('Target', axis=1)

# Buat 'y' dengan HANYA memilih kolom 'Target'.
y = df_encoded['Target']

# Panggil fungsi untuk membagi data.
#  - Gunakan 'stratify=y' agar proporsi kelas di train/test set sama.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

### SELESAI CODE ###

print("Jumlah data total: ",len(X))
print("Jumlah data latih: ",len(X_train))
print("Jumlah data test: ",len(X_test))

Jumlah data total:  10
Jumlah data latih:  8
Jumlah data test:  2

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [40]:
# Buatlah model klasifikasi menggunakan Decision Tree

### MULAI CODE ###

# 1. Buat (instantiate) objek model Decision Tree
#    Gunakan 'random_state=42' agar hasilnya konsisten
decision_tree_model = DecisionTreeClassifier(random_state=42)

# 2. Latih (fit) model dengan data training (X_train dan y_train)
decision_tree_model.fit(X_train, y_train)

### SELESAI CODE ###

DecisionTreeClassifier(random_state=42)

In [41]:
# Menyimpan Model

### MULAI CODE ###

joblib.dump(decision_tree_model, 'decision_tree_model.h5')

### SELESAI CODE ###

['decision_tree_model.h5']

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**

**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [42]:
# Melatih model menggunakan algoritma klasifikasi scikit-learn selain Decision Tree. (Contoh: RandomForestClassifier)

### MULAI CODE ###

# Buat (instantiate) objek model baru
new_model = RandomForestClassifier(random_state=42)

# Latih (fit) model dengan data training (X_train dan y_train)
new_model.fit(X_train, y_train)

### SELESAI CODE ###

RandomForestClassifier(random_state=42)

In [43]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada seluruh algoritma yang sudah dibuat.

### MULAI CODE ###

# Buat prediksi pada data 'X_test' menggunakan kedua model
y_pred_dt = decision_tree_model.predict(X_test)
y_pred_new = new_model.predict(X_test)

# Tampilkan classification_report untuk Decision Tree
print("Decision Tree Performance")
print(classification_report(y_test, y_pred_dt))

print("="*50)

# Tampilkan classification_report untuk New Model
print("New Model Performance")
print(classification_report(y_test, y_pred_new))

### SELESAI CODE ###

Decision Tree Performance
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

==================================================
New Model Performance
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

c:\Users\Muh Fajri\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Muh Fajri\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Muh Fajri\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [44]:
# Menyimpan Model Selain Decision Tree
# Model ini bisa lebih dari satu

### MULAI CODE ###

joblib.dump(new_model, 'explore_random_forest_classification.h5')

### SELESAI CODE ###

['explore_random_forest_classification.h5']

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [45]:
# Lakukan Hyperparameter Tuning dan Latih ulang.
# Lakukan dalam satu cell ini saja.

### MULAI CODE ###

# Tentukan Hyperparameter yang akan di-tuning
params = {'n_estimators': [100, 200],
          'max_depth': [None, 10, 20],
          'min_samples_split': [2, 5, 10],}

# Buat (instantiate) objek dari algoritma tuning
#  - 'estimator': Model yang akan di-tuning
#  - 'params': Hyperparameter yang sudah kita tentukan
new_model_tuned = GridSearchCV(
    estimator = RandomForestClassifier(random_state=42),
    param_grid = params,
    cv = 5,
    scoring = 'accuracy'
)

# Latih objek model dengan data training (X_train dan y_train)
new_model_tuned.fit(X_train, y_train)

### SELESAI CODE ###

ValueError: n_splits=5 cannot be greater than the number of members in each class.

In [ ]:
# Menampilkan hasil evaluasi akurasi, presisi, recall, dan F1-Score pada algoritma yang sudah dituning.

### MULAI CODE ###

# Buat prediksi pada 'X_test' Gunakan model yang sudah di-tuning
y_pred_tuning = new_model_tuned.predict(X_test)

# Tampilkan classification_report untuk model yang sudah di-tuning
print("Tuned Model Performance")
print(classification_report(y_test, y_pred_tuning))

### SELESAI CODE ###

In [ ]:
# Menyimpan Model hasil tuning

### MULAI CODE

joblib.dump(new_model_tuned, 'tuning_classification.h5')

### SELESAI CODE ###

End of Code